version: 2
jobs:
  branches:
      only:
      - release # list of branches to build
  build:
    docker:
      - image: "circleci/node:12"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: "npm install"
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Build Project'
          command: 'npm build'
      - run:
          name: "Deploy to Firebase Hosting"
          command: "./node_modules/.bin/firebase deploy --only hosting:tool-builder --token=$FIREBASE_TOKEN"