version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
jobs:
    build:
        docker:
            - image: circleci/node:12.9.1-browsers
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  # fallback to using the latest cache if no exact match is found
                  - v1-dependencies-


            - run:
                  name: Install Dependencies
                  command: yarn install

            - save_cache:
                paths:
                  - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            - snyk/scan:
                  fail-on-issues: false
                  monitor-on-build: false
                  severity-threshold: high

            - run: yarn lint

            - run: yarn size

            - run:
                  name: Build
                  command: yarn build

            - run:
                  name: Firebase Deploy
                  command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting